### ISSUE TITLE
Please create a first (pre-)release

### ISSUE THREAD

**Issue by hpreusse** [Castaglia/proftpd-mod_sftp_ldap#9]
Here in debian we got the [request](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1028630) to create an Debian package of that module. Please be so kind to create a first (pre-)release having a version number, we can download. Many thanks!

**Comment by Castaglia** [comment]
Done; see: https://github.com/Castaglia/proftpd-mod_sftp_ldap/releases/tag/v0.2
